# GRPC Server.
grpc:
  address: ":8001"
  name: "jh_user_service"
  logPath: ""
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"

# Consul 配置
consul:
  addr: "localhost:8500"
  serviceName: "user-service"
  servicePort: 8001
  serviceAddr: "192.168.254.141"

# Global logging - JSON格式
logger:
  level: "all"
  stdout: true
  # 使用JSON格式输出
  format: "json"
  # 时间格式
  timeFormat: "2006-01-02T15:04:05.000Z07:00"

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:654321@tcp(localhost:3306)/jh_site"
    debug: true
