# GRPC Server.
grpc:
  address: ":8001"
  name: "jh_user_service"
  logPath: ""
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"

# Consul 配置
consul:
  addr: "172.19.0.29:8500"
  serviceName: "user-service"
  servicePort: 8001
  serviceAddr: "172.19.0.31"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:654321@tcp(172.19.0.4:3306)/test"
    debug: true
